Give back Writer on Encoder::finish()
ComunidadAylas/vorbis-rs pull request #8
Opened 2023-04-13 14:10 UTC by algesten

If using a `Cursor<Vec<u8>>` to write to memory, or an auto-removing temp file (https://docs.rs/tempfile/3.5.0/tempfile/fn.tempfile.html#resource-leaking), there needs to be some way of getting the captured writer back.

I suggest adding the writer as output of the `finish` call, so we can get ownership of it back.

2023-04-13 14:38 UTC, AlexTMjugador commented
Thank you for using this crate and submitting a PR! :heart:

Since `finish` does not currently return anything interesting on success, I think that it is a sensible idea to yield the sink back.

However, the standard library provides a [`by_ref` method for every `Write`](https://doc.rust-lang.org/std/io/trait.Write.html#method.by_ref), the purpose of which is to avoid transferring ownership of a writer to methods and data types that take a `Write` implementation, such as `VorbisEncoder`, by mutably borrowing it instead.

Does your PR solve any problem that `by_ref` does not? (Just asking, it could be merged even if it didn't :smile:)

2023-04-13 21:02 UTC, algesten commented
@AlexTMjugador thanks for the prompt reply!

My problem with using a borrowed writer is that the borrow lifetime parameter must leak upward into any wrapping struct. 

In my case I have a struct `Output` which holds both the vorbis encoder as well as a mixer since they are used together.

```rs
struct Output {
  encoder: Encoder<File>,
  mixer: Mixer,
}
```

If this was `Encoder<&'a mut File>` it would force me to also have `Output<'a>`. It's possible, but "taints" my abstractions and breaks my encapsulation.

2023-04-14 10:33 UTC, AlexTMjugador requested changes
Alright, that lifetime parameter propagation avoidance use case convinced me! I'd like to merge this after a little change :wink:

2023-04-14 10:33 UTC, AlexTMjugador commented on packages/vorbis_rs/src/encoder/encoder_impl.rs
>  	finished: bool
Wrapping the writer in an `Option` is a good idea that relies only on safe code, but requires destructuring or calling `unwrap` or `expect` every time it is used, which is not particularly elegant.

Since this crate has to rely on unsafe code anyway, I think that a potentially more efficient and elegant approach would be to wrap the sink in `ManuallyDrop` and get rid of the `finished` field, by calling `mem::forget(self)` on `finish` (`finish` is meant to tear down the encoder like `Drop`, but returning a result).

For your reference, I've cobbled together a proof of concept of this approach on [a Rust Playground code snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6c91796e31a8eba2bc00d9b75a3ab6fb).

2023-04-14 10:43 UTC, AlexTMjugador approved these changes
Nevermind the previous review, other `VorbisEncoder` fields have destructors that must be run when tearing down an encoder, and `unwrap`ping the sink around is easier to reason about for correctness.

Merging this! :tada:

2023-04-14 10:43 UTC, merged

2023-04-14 11:23 UTC, algesten commented
Thanks!

2023-04-14 14:46 UTC, AlexTMjugador commented
This change has just been published in [`vorbis_rs` v0.3.0](https://github.com/ComunidadAylas/vorbis-rs/releases/tag/v0.3.0)! :tada:

I also took the opportunity to do some minor tidy-ups to the codebase.